name: emvo_assessment
description: Assessment engine package for Emvo.
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  emvo_core:
    path: ../emvo_core
  emvo_ui:
    path: ../emvo_ui
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  shared_preferences: ^2.3.3

flutter:
  assets:
    - lib/src/data/questions.json
    - lib/src/data/work.json
    - lib/src/data/reactions.json
    - lib/src/data/leadership.json
    - lib/src/data/growth.json

dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  integration_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1
